#include "lib/webserver/style.h"
#include "lib/webserver/javascript.h"

char html[] = 
"\n<!DOCTYPE html>"
"\n<html lang=\"pt-BR\">"
"\n<head>"
    "\n<meta charset=\"UTF-8\">"
    "\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    "\n<title>Monitoramento Climático</title>"
    "\n <style>" STYLE_PAGE
    "</style>"
"\n</head>"
"\n<body>"
    "\n<header>"
        "\n<div class=\"container\">"
            "\n<h1>Monitoramento Climático</h1>"
        "\n</div>"
    "\n</header>"
    
    "\n<div class=\"container\">"
        "\n<div class=\"config-panel\">"
            "\n<h2>Configurações</h2>"
            
            "\n<div class=\"config-forms\">"
                "\n<!-- Formulário de Temperatura -->"
                "\n<form id=\"temp-config\" class=\"config-form\">"
                    "\n<h3>Limites de Temperatura</h3>"
                    "\n<div class=\"form-group\">"
                        "\n<label for=\"min-temp\">Mínima (°C):</label>"
                        "\n<input type=\"number\" step=\"0.1\" id=\"min-temp\" required>"
                    "\n</div>"
                    "\n<div class=\"form-group\">"
                        "\n<label for=\"max-temp\">Máxima (°C):</label>"
                        "\n<input type=\"number\" step=\"0.1\" id=\"max-temp\" required>"
                    "\n</div>"
                    "\n<button type=\"submit\">Salvar</button>"
                "\n</form>"
                
                "\n<!-- Formulário de Umidade -->"
                "\n<form id=\"humidity-config\" class=\"config-form\">"
                    "\n<h3>Limites de Umidade</h3>"
                    "\n<div class=\"form-group\">"
                        "\n<label for=\"min-humidity\">Mínima (%):</label>"
                        "\n<input type=\"number\" step=\"0.1\" id=\"min-humidity\" required>"
                    "\n</div>"
                    "\n<div class=\"form-group\">"
                        "\n<label for=\"max-humidity\">Máxima (%):</label>"
                        "\n<input type=\"number\" step=\"0.1\" id=\"max-humidity\" required>"
                    "\n</div>"
                    "\n<button type=\"submit\">Salvar</button>"
                "\n</form>"
                
                "\n<!-- Formulário de Pressão -->"
                "\n<form id=\"pressure-config\" class=\"config-form\">"
                    "\n<h3>Pressão ao Nível do Mar</h3>"
                    "\n<div class=\"form-group\">"
                        "\n<label for=\"sea-level-pressure\">Pressão (Pa):</label>"
                        "\n<input type=\"number\" step=\"0.1\" id=\"sea-level-pressure\" value=\"101325.0\" required>"
                    "\n</div>"
                    "\n<button type=\"submit\">Salvar</button>"
                "\n</form>"
            "\n</div>"
        "\n</div>"

        "\n<div class=\"dashboard\">"
            "\n<!-- Sensor AHT -->"
            "\n<div class=\"sensor-card\">"
                "\n<div class=\"sensor-header\">"
                    "\n<div class=\"sensor-icon\">🌡️</div>"
                    "\n<h2 class=\"sensor-title\">Sensor AHT</h2>"
                "\n</div>"
                "\n<div class=\"data-item\">"
                    "\n<span class=\"data-label\">Temperatura:</span>"
                    "\n<span class=\"data-value temp\" id=\"aht-temp\">-- °C</span>"
                    "\n<span class=\"data-alert\" id=\"temp-alert\"></span>"
                "\n</div>"
                "\n<div class=\"data-item\">"
                    "\n<span class=\"data-label\">Umidade:</span>"
                    "\n<span class=\"data-value humidity\" id=\"aht-humidity\">-- %</span>"
                    "\n<span class=\"data-alert\" id=\"humidity-alert\"></span>"
                "\n</div>"
                "\n<div class=\"last-update\" id=\"aht-update\">Última atualização: --</div>"
            "\n</div>"
            
            "\n<!-- Sensor BMP -->"
            "\n<div class=\"sensor-card\">"
                "\n<div class=\"sensor-header\">"
                    "\n<div class=\"sensor-icon\">📊</div>"
                    "\n<h2 class=\"sensor-title\">Sensor BMP</h2>"
                "\n</div>"
                "\n<div class=\"data-item\">"
                    "\n<span class=\"data-label\">Pressão:</span>"
                    "\n<span class=\"data-value pressure\" id=\"bmp-pressure\">-- hPa</span>"
                "\n</div>"
                "\n<div class=\"data-item\">"
                    "\n<span class=\"data-label\">Temperatura:</span>"
                    "\n<span class=\"data-value temp\" id=\"bmp-temp\">-- °C</span>"
                "\n</div>"
                "\n<div class=\"data-item\">"
                    "\n<span class=\"data-label\">Altitude:</span>"
                    "\n<span class=\"data-value altitude\" id=\"bmp-altitude\">-- m</span>"
                "\n</div>"
                "\n<div class=\"last-update\" id=\"bmp-update\">Última atualização: --</div>"
            "\n</div>"
            
            "\n<!-- Média de Temperatura -->"
            "\n<div class=\"sensor-card\">"
                "\n<div class=\"sensor-header\">"
                    "\n<div class=\"sensor-icon\">📈</div>"
                    "\n<h2 class=\"sensor-title\">Média de Temperatura</h2>"
                "\n</div>"
                "\n<div class=\"data-item\">"
                    "\n<span class=\"data-label\">Média (AHT + BMP):</span>"
                    "\n<span class=\"data-value average\" id=\"avg-temp\">-- °C</span>"
                "\n</div>"
                "\n<div class=\"last-update\" id=\"avg-update\">Última atualização: --</div>"
            "\n</div>"
        "\n</div>"
        
        "\n<div class=\"charts-container\">"
            "\n<div class=\"chart-container\">"
                "\n<h2 class=\"chart-title\">Histórico de Temperatura</h2>"
                "\n<canvas id=\"tempChart\"></canvas>"
            "\n</div>"
            
            "\n<div class=\"chart-container\">"
                "\n<h2 class=\"chart-title\">Histórico de Umidade</h2>"
                "\n<canvas id=\"humidityChart\"></canvas>"
            "\n</div>"
            
            "\n<div class=\"chart-container\">"
                "\n<h2 class=\"chart-title\">Histórico de Pressão Atmosférica</h2>"
                "\n<canvas id=\"pressureChart\"></canvas>"
            "\n</div>"
        "\n</div>"
    "\n</div>"
    
    "\n<script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>"
    "\n<script>" SERVER_CODE
    "\n </script>"
"\n</body>"
"\n</html>";